version: "3.7"
services:

  client-react:
    container_name: client-react
    image: online-survey-client
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 80:3000

  node-server:
    container_name: node-server
    image: online-survey-server
    build:
      context: server
      dockerfile: Dockerfile
